-- Initial persistence schema for Dev Week 03.
-- IDs are generated by the application so the same contract works with
-- SQLite fixtures and PostgreSQL production storage.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'created'
        CHECK (status IN ('created', 'processing', 'completed', 'failed')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transcript_segments (
    segment_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision >= 1),
    is_final INTEGER NOT NULL DEFAULT 0 CHECK (is_final IN (0, 1)),
    start_ms INTEGER NOT NULL CHECK (start_ms >= 0),
    end_ms INTEGER NOT NULL CHECK (end_ms >= start_ms),
    speaker_id TEXT NOT NULL,
    text TEXT NOT NULL,
    asr_confidence REAL CHECK (asr_confidence IS NULL OR (asr_confidence >= 0 AND asr_confidence <= 1)),
    created_at TEXT NOT NULL,
    PRIMARY KEY (segment_id, revision),
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transcript_segments_session_time
    ON transcript_segments(session_id, start_ms, end_ms);

CREATE TABLE IF NOT EXISTS summaries (
    summary_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    version INTEGER NOT NULL CHECK (version >= 1),
    text TEXT NOT NULL,
    source_segment_ids TEXT NOT NULL DEFAULT '[]',
    is_final INTEGER NOT NULL DEFAULT 0 CHECK (is_final IN (0, 1)),
    created_at TEXT NOT NULL,
    PRIMARY KEY (summary_id, version),
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_summaries_session_version
    ON summaries(session_id, version DESC);

CREATE TABLE IF NOT EXISTS extracted_items (
    item_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    item_type TEXT NOT NULL
        CHECK (item_type IN ('person', 'topic', 'decision', 'action_item')),
    text TEXT NOT NULL,
    confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    evidence_segment_ids TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_extracted_items_session_type
    ON extracted_items(session_id, item_type);

CREATE TABLE IF NOT EXISTS domain_events (
    event_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_domain_events_session_created
    ON domain_events(session_id, created_at, event_id);
